version: '3.3'

services:

  web:
    build:
      context: .
      dockerfile: ./credit_guard/docker/Dockerfile
    entrypoint: "./credit_guard/docker/entrypoints/runserver"

    container_name: credit-guard-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - main

  db:
    image: postgres:latest
    container_name: credit-guard-db
    ports:
      - "5435:5432"
    volumes:
      - credit_guard_db_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    networks:
      - main

volumes:
  credit_guard_db_volume:

networks:
  main:
    driver: bridge