# Generated by Django 5.0.6 on 2024-06-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_created_at_card_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="card_number",
        ),
        migrations.RemoveField(
            model_name="card",
            name="ccv",
        ),
    ]
